### ISSUE TITLE
Sound and Setting Icons are off in FireFox

### ISSUE THREAD

**Issue by TheBinaryBee** [Zarel/Pokemon-Showdown#2421]
When using the latest FireFox Developer Browser, the sound and setting icons in the upper right are moved to the bottom.
![untitled](https://cloud.githubusercontent.com/assets/3207763/13024898/d2f25822-d1fc-11e5-9ab3-5f9d4db2a6d3.png)

A fix that should work is adding
```css
.userbar button.icon{
    line-height:10px;
}
```
